apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: backend-django
spec:
        replicas: 2
        minReadySeconds: 15
        strategy:
                type: RollingUpdate
                rollingUpdate:
                        maxSurge: 1
                        maxUnavailable: 1
        template:
                metadata:
                        labels:
                                app: backend-django
                spec:
                        containers:
                                - image: trevahok/todorest:gunicorn
                                  imagePullPolicy: Always
                                  name: backend-django
                                  ports:
                                          - containerPort: 8000


