apiVersion: v1
kind: Pod
metadata: 
        name: frontend-react
        labels:
                app: frontend-react
spec:
        containers:
                - image: trevahok/todoreact
                  name: frontend-react
                  ports:
                          - containerPort: 80
